name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install DeepXDE
      run: |
        pip install deepxde
        DDEBACKEND=tensorflow.compat.v1 python -c "import deepxde"
        echo pwd
