name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install DeepXDE
      run: |
        pip install -r requirements.txt
        DDEBACKEND=tensorflow.compat.v1 python -c "import deepxde"
        echo pwd
